demoDjango/AppBlog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogDeleteView

app_name = "AppBlog"

urlpatterns = [
    path("list/", BlogListView.as_view(), name="list"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("detail/<int:pk>", BlogDetailView.as_view(), name="detail"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="delete"),
]

demoDjango/AppCar/urls.py
from django.urls import path
from .views import CarListView, CarDetailView, CarCreateView, CarDeleteView

app_name = "AppCar"

urlpatterns = [
    path("list/", CarListView.as_view(), name="list"),
    path("create/", CarCreateView.as_view(), name="create"),
    path("detail/<int:pk>", CarDetailView.as_view(), name="detail"),
    path("delete/<int:pk>", CarDeleteView.as_view(), name="delete"),
]

demoDjango/demoDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('car/', include("AppCar.urls")),
    path('blog/', include("AppBlog.urls")),
    path('admin/', admin.site.urls),
]

demoDjango/AppBlog/models.py
from django.db import models
from django.urls import reverse_lazy


class Blog(models.Model):
    title = models.CharField(max_length=32)
    content = models.TextField()

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse_lazy("AppBlog:detail", kwargs={"pk": self.pk})

demoDjango/AppCar/models.py
from django.db import models
from django.urls import reverse_lazy


class Car(models.Model):
    brand = models.CharField(max_length=32)
    model = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.brand} {self.model}"

    def get_absolute_url(self):
        return reverse_lazy("AppCar:detail", kwargs={"pk": self.pk})

demoDjango/AppBlog/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from .models import Blog
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Blog List"
        return context


class BlogDetailView(DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Blog Detail"
        return context


class BlogCreateView(CreateView):
    model = Blog
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Blog Form"
        return context


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("AppBlog:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Blog Delete"
        return context

demoDjango/AppCar/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from .models import Car
from django.urls import reverse_lazy


class CarListView(ListView):
    model = Car

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Car List"
        return context


class CarDetailView(DetailView):
    model = Car

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Car Detail"
        return context


class CarCreateView(CreateView):
    model = Car
    fields = "__all__"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Car Form"
        return context


class CarDeleteView(DeleteView):
    model = Car
    success_url = reverse_lazy("AppCar:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Car Delete"
        return context

demoDjango/demoDjango/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "index.html"

demoDjango/AppBlog/templates/AppBlog/blog_confirm_delete.html
{% extends "layout/base.html" %} {% block main %} {% load django_bootstrap5 %}

<div class="container p-4">
  <form method="post">
    {% csrf_token %} {% bootstrap_form form %}
    <h4>Delete Confirm?</h4>
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
</div>

{% endblock %}

demoDjango/AppBlog/templates/AppBlog/blog_detail.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <h4>Title: {{blog.title|capfirst}}</h4>
  <p>Content: {{blog.content}}</p>
  <a href="{% url 'AppBlog:delete' blog.pk %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

demoDjango/AppBlog/templates/AppBlog/blog_form.html
{% extends "layout/base.html" %} {% block main %} {% load django_bootstrap5 %}
<form method="post" class="form col-6 mx-auto">
  {% csrf_token %} {% bootstrap_form form %} 
  {% bootstrap_button button_type="submit" content="OK" %} 
  {% bootstrap_button button_type="reset" content="Cancel" %}
</form>
{% endblock %}

demoDjango/AppBlog/templates/AppBlog/blog_list.html
{% extends "layout/base.html" %} {% block main %}

<div class="d-flex p-3">
  <h4 class="h4 me-auto">Blog List</h4>
  <a class="btn btn-primary" href="{% url 'AppBlog:create' %}">Create</a>
</div>

<ul class="list-group">
  {% for blog in blog_list %}
  <li class="list-group-item">
    <h5>
      <a href="{% url 'AppBlog:detail' blog.pk %}">{{blog.title|capfirst}}</a>
    </h5>
    <p>{{blog.content}}</p>
  </li>
  {% endfor %}
</ul>

{% endblock %}

demoDjango/AppCar/templates/AppCar/car_confirm_delete.html
{% extends "layout/base.html" %} {% block main %} {% load django_bootstrap5 %}

<div class="container p-4">
  <form method="post">
    {% csrf_token %} {% bootstrap_form form %}
    <h4>Delete Confirm?</h4>
    <p>{{model}}</p>
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
</div>

{% endblock %}

demoDjango/AppCar/templates/AppCar/car_detail.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <h4>Brand: {{car.brand|capfirst}}</h4>
  <p>Model: {{car.model}}</p>
  <a href="{% url 'AppCar:delete' car.pk %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

demoDjango/AppCar/templates/AppCar/car_form.html
{% extends "layout/base.html" %} {% block main %} {% load django_bootstrap5 %}
<form method="post" class="form col-6 mx-auto">
  {% csrf_token %} {% bootstrap_form form %} 
  {% bootstrap_button button_type="submit" content="OK" %} 
  {% bootstrap_button button_type="reset" content="Cancel" %}
</form>
{% endblock %}

demoDjango/AppCar/templates/AppCar/car_list.html
{% extends "layout/base.html" %} {% block main %}

<div class="d-flex p-3">
  <h4 class="h4 me-auto">Car List</h4>
  <a class="btn btn-primary" href="{% url 'AppCar:create' %}">Create</a>
</div>

<ul class="list-group">
  {% for car in car_list %}
  <li class="list-group-item">
    <h5>
      <a href="{% url 'AppCar:detail' car.pk %}">{{car.brand|capfirst}}</a>
    </h5>
    <p>{{car.model}}</p>
  </li>
  {% endfor %}
</ul>

{% endblock %}

demoDjango/templates/index.html
{% extends "layout/base.html" %} {% block main %}
<h1>Home</h1>


{% endblock %}

demoDjango/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include "layout/nav.html" %}
    <main class="container">{% block main %}{% endblock %}</main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

demoDjango/templates/layout/nav.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"> Demo Simple Django </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'home' %}"
          >
            Home
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppCar:list' %}"> Car List </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppBlog:list' %}"> Blog List </a>
        </li>
      </ul>
    </div>
  </div>
</nav>